### PR TITLE
Fixed tests on windows

### PR DESCRIPTION
**Pull request by amitsarangi**
Issue for reference: https://github.com/developit/preact-cli/issues/555

A project created through preact-cli default template was unable to run tests on windows, which this PR addresses. 
  
**Summary of changes**
-  Moved the tests directory and .babelrc to the root directory.
- Changed jest config. Removed the `./tests` directory passed from `npm tun test` command and added `testRegex` to jest options.
- Added jest option `testPathIgnorePatterns` to ignore `__mocks__` directory.
- Removed unused dependancy from the `header.test.js` file.
- Tested in Windows and OSX.

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]

**Review by reznord — APPROVED** [review]
Oh nice work 👍😄

**Comment by lukeed** [comment]
Just FYI, whenever a `preactjs-templates` repo changes (especially file structure), Preact CLI's tests have to update.

Edit 1: For future reference (https://github.com/developit/preact-cli/pull/639/files/bc091df9ee7ba2e5a8d3d33235658d88bf95e80d#diff-86d10f55c40b83fe7be95092e4db252c)

**Comment by amitsarangi** [comment]
@lukeed I see from the code that preact-cli@next is testing only the default template. Do we need to add support for testing all templates provided through the `preactjs-templates` repository ?

**Comment by lukeed** [comment]
Nope, `default` is the most involved, so just rolling with that should be fine. We have `TODO` notes in the tests to attach the others, but the history of `default` evolvement has shown that it gets messy fairly quickly 😆

**Pull request merged**
